# Generated by Django 5.1.7 on 2025-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_drug_updated_at_order_updated_at_supplier_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='location_coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
